services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GENIE_ENV=dev
    depends_on:
      - db
    volumes:
      - .:/app
    tty: true
    command: julia -e "using Pkg; Pkg.activate(\".\"); using Genie; Genie.loadapp(); up(host = \"0.0.0.0\", async = false);"

  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goat
      TZ: Asia/Tokyo
    volumes:
      - ./my.ini:/etc/mysql/conf.d/my.cnf
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql